name: shopping
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Ensures compatibility with Flutter SDK 3.x

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  shared_preferences: ^2.0.15
  logger: ^1.1.0
  flutter_riverpod: ^2.0.0
  iconsax: ^0.0.8
  image_picker: ^1.0.4
  cached_network_image: ^3.2.0
  provider: ^6.0.0
  charts_flutter: ^0.12.0 # эсвэл шинэчилсэн форк хувилбар
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/2.jpg
    - assets/12.jpg
    - assets/123.jpg
    - assets/12345.png
  fonts:
    - family: RobotoSerif
      fonts:
        - asset: assets/fonts/Roboto_Serif/static/RobotoSerif-Regular.ttf

analyzer:
  enable-experiment:
    - super-parameters
